### ISSUE TITLE
setuptools problem - creates requires.txt

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-bears#161] opened 2016-03-05 17:18 UTC
It seems that when im trying to use setuptools to install coala-bears as a dependecy, it doesnt find ``requirements.txt`` .After further investigation, when im building coala-bears with ``./setup.py sdist bdist`` , it has ``requires.txt`` in it, instead of ``requirements.txt`` .

**Comment by AbdealiJK** [comment] 2016-03-05 18:34
AFAIK
The `install_requires` creates the requires.txt - its meant to be there.
It has the same data as requirements.txt because we read it in the setup.py and set it to be the same
The requirements.txt is not being copied because there's no MANIFEST

This is expected behaviour

**Comment by AbdealiJK** [comment] 2016-03-15 01:59
@Adrianzatreanu I'm closing this as it seems to be expected behaviour.
Reopen if you think it should not be closed

**Closed by AbdealiJK** 2016-03-15 01:59 UTC
Labels: difficulty/medium, importance/medium
