### ISSUE TITLE
Code Duplication Bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#33] opened 2016-02-21 15:07 UTC
_From @sils1297 on December 22, 2015 13:32_

Would be nice to have a code duplication bear for other languages than C. https://github.com/codeclimate/codeclimate-duplication provides that for some languages, would be awesome to integrate with that.

_Copied from original issue: coala-analyzer/coala#1158_

**Comment by ravinimmi** [comment] 2016-02-22 19:40
@sils1297 I want to do this.

**Comment by ravinimmi** [comment] 2016-02-23 07:19
@sils1297 What do you think about [simian](http://www.harukizaemon.com/simian/index.html). Its free for open source projects. But it needs java for it to run.

**Comment by sils1297** [comment] 2016-02-23 10:43
I'd rather avoid shipping bears with coala that pull in proprietary
software. At least I am very idealistic about coala and by default we
definitely should not ship with anything proprietary.

2016-02-23 8:19 GMT+01:00 Ravi Kumar Nimmi <notifications@github.com>:

**Comment by Adrianzatreanu** [comment] 2016-03-28 19:18
@ravinimmi it's been a while, you still on this :) ?

**Comment by ravinimmi** [comment] 2016-03-28 22:12
@Adrianzatreanu @sils1297 Sorry for the delay. I am not currently working on this. Please unassign.

**Comment by Uran198** [comment] 2016-04-06 06:58
Codeclimate uses it's own configuration file, so should we reuse their file, or try to present settings via coala? I thinks the second variant is more preferable, but I cannot figure out how to handle settings thresholds for each language. One way, is to use `dict` for that, but in that case would the settings be straight forward?

**Comment by sils1297** [comment] 2016-04-06 08:23
Ideally the user never notices he's using something else in the back so we want the user to be able to set stuff via the coafile. I don't understand your problem with it fully though.

**Comment by Uran198** [comment] 2016-04-06 11:27
Codeclimate seems to be unable to work without the configuration file. We can try creating this file before it's run and deleting afterwards, but I'm not sure that this is a good idea.

**Comment by AbdealiJK** [comment] 2016-04-06 11:31
We already do that, check the `config_file` and `generate_config_file` in
Lint

**Comment by Uran198** [comment] 2016-04-06 12:26
@AbdealiJK Thanks, but it seems I can't use that ones, cause file has to have specific name i. e. `.codeclimate.yml`.

**Comment by sils1297** [comment] 2016-04-06 12:28
@Uran198 I think you should add a param to Lint to make that possible instead of reimplementing it

**Comment by Uran198** [comment] 2016-04-06 12:50
@sils1297 Yes, that's nice.
Although there are still several details, I want to discuss:
- Unlike `coala` `codeclimate` configures paths that it's excludes, so to make it work I'll have to from all possible paths extract the ones that need checking.
- The bear has to be both linter and `GlobalBear` it seems. There are no examples of such, so I'm not sure if it's OK to do it. While doing so, I'll need to call `self.lint('')` which isn't probably what it was designed for.

**Comment by Adrianzatreanu** [comment] 2016-04-06 14:40
as i know this has also been around for a couple of days (mostly weeks) and it supports quite a few languages: https://github.com/coala-analyzer/coala-bears/pull/263/commits/796e4e57b431a49a6a88a437da129a871c7217ee but it wasn't attached to any issue

**Comment by Uran198** [comment] 2016-04-14 07:34
So, would we want both code duplication checking routines?

**Comment by sils1297** [comment] 2016-04-14 07:54
I'd close this for now, PMD is way easier for us right now and we have to go through all languages and determine what we need for them at some point anyway. With all the problems of this and us having something already...

**Comment by Uran198** [comment] 2016-04-15 16:46
I'm closing this for now in favour of https://github.com/coala-analyzer/coala-bears/pull/263

**Closed by Uran198** 2016-04-15 16:46 UTC
Labels: difficulty/medium, importance/low, type/feature
