### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by vivek425ster** [coala-analyzer/coala-bears#202] opened 2016-03-10 15:38 UTC
Attached is the log when I ran py.test
http://pastebin.com/f5MEsZDF

**Comment by Makman2** [comment] 2016-03-10 16:27
Could you please share also which commandos you used to get coala-bears and how do you executed the tests? If you use a virtual environment or similar please also post the commandos used for setup,  activation etc. :)

Which platform do you use btw?

**Comment by vivek425ster** [comment] 2016-03-10 16:46
@Makman2 Hi,
I am working on ubuntu14.04 x86-64. 
I followed these instructions to install coala-bears. 
http://coala.readthedocs.org/en/latest/Users/Install.html#installing-coala-from-source
I din't use virtual environment. I installed it directly using sudo.
I executed it using `py.test  --resultlog`
and this is the initial line:
 `platform linux -- Python 3.4.3, pytest-2.9.0, py-1.4.31, pluggy-0.3.1`

**Comment by Makman2** [comment] 2016-03-10 17:15
I see you don't use all plugins we need, like coverage.
Please do `sudo pip3 install -r test-requirements.txt --upgrade` inside the coala-bears repo to install all test-requirement an re-execute tests.
Tried on ubuntu 14.04 latest packages (except kernel upgrades), but can't reproduce.

**Comment by Makman2** [comment] 2016-03-10 17:41
could you again provide the complete log? with commando and also the plugins, so just everything?

**Comment by vivek425ster** [comment] 2016-03-10 17:47
The complete log which is present in stdout: http://pastebin.com/uK5FAxHd
The log as a result of py.test --resultlog=logfile : http://pastebin.com/mJRGARUW

**Comment by Makman2** [comment] 2016-03-10 18:01
alright I got your output now, this is for npm packages. Though that's an npm issue, e.g. executing bootlint itself using `bootlint --version` yields:
```
mak@ubuntu:~/dev/coala-bears(master)$ bootlint --version
/usr/bin/env: node: No such file or directory
```

**Comment by Makman2** [comment] 2016-03-10 18:12
Alright you need to also install `nodejs-legacy` and then install your node packages. Then this should work :+1:

**Comment by sils1297** [comment] 2016-03-10 18:16
@Makman2 the issue is that tests should be skipped automatically! If they
aren't the bears won't have proper error messages as well

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-10 19:12 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by vivek425ster** [comment] 2016-03-10 18:17
@Makman2 
I installed `nodejs-legacy` using `sudo apt-get install nodejs-legacy`
Still 7 tests are failing.
Also should i add `nodejs-legacy` in the deps.sh file or package.json ?

**Comment by Makman2** [comment] 2016-03-10 18:51
no `nodejs-legacy` is an aptitude package, not an npm package :)
and `deps.sh` is for our CI, you don't need to modify it since it works already :+1:

@sils1297 test skipping is not the issue here. the executables do exist but somehow they don't start because `node` seems not to be found (though it exists too). This is a dependency problem inside Ubuntu, as stated in my linked issue^^

**Comment by Makman2** [comment] 2016-03-10 18:58
@vivek425ster btw please add again your test output, I can't see what tests are still failing :+1:

**Comment by AbdealiJK** [comment] 2016-03-10 23:41
We don't check in bears if the programming language is installed. Ie if java or node or ruby or r is not installed ... Tests will fail.
We only check for the package. We discussed this earlier and decided it's the package managers role to install all deps of a linter.
The reason for this confusion is a name conflict between an existing package node and the nodejs in Ubuntu. So this is a big in Ubuntu repos really ...

-----Original Message-----

**Comment by vivek425ster** [comment] 2016-03-11 05:34
@Makman2 http://pastebin.com/ZseqmqME

**Comment by AbdealiJK** [comment] 2016-03-11 05:50
Here's my analysis:

 - GoVetBear: This is a known issue (https://github.com/coala-analyzer/coala-bears/issues/49) and should be fixed. If you want it to pass for now, install `golang-go.tools` using apt-get
 - ProseLintBear: This is another issue I've faced before. This happens when you use the 0.12.x version of nodejs (which is used in Ubuntu's apt-get). nodeJS has come up to v5.x.x and it would be best if you installed nvm and used that to get the latest node. It's a proselint bug - proselint doesnt work with old nodes I guess ?
 - LanguageToolBear: Now this one is interesting. I **think** this could also be because you use an older version of nodejs. But I cannot reproduce it right now.

**Comment by AbdealiJK** [comment] 2016-03-11 05:54
@vivek425ster Have you installed various web technologies in your laptop ?
I remember xmpp using the port 8081 and maybe that is clashing with LanguageTool ?
Or have you used port 8081 for anything else at all that you know of ?

**Comment by AbdealiJK** [comment] 2016-05-24 04:51
@vivek425ster still facing this ? Was it solved ?

**Comment by vivek425ster** [comment] 2016-05-24 05:47
@AbdealiJK did not try it afterwards .

**Comment by AbdealiJK** [comment] 2016-08-31 20:37
@vivek425ster Closing this as it is very old and nobody else has faced it since then.
I do think it was a system configuration where some port was clashing.

If someone faces this issue again, feel free to reopen.

**Closed by AbdealiJK** 2016-08-31 20:37 UTC
Labels: type/bug, type/test
