### ISSUE TITLE
ESLintBear still fails !

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#727] opened 2016-08-29 11:48 UTC
type/bug

**Comment by AbdealiJK** [comment] 2016-08-31 17:57
So, to clarify ... the issue is about the fact that ESLintBear breaks down if the file has no issues ?
The unittests don't seem to fail though. Weird.

**Comment by AbdealiJK** [comment] 2016-08-31 17:59
Nice. The complete ESLintBear is broken.
The tests pass but the output is given is that of the `eslint --help` because eslint has some problem with the command running by Lint.

**Comment by sils1297** [comment] 2016-08-31 18:19
Holy shit

**Comment by sils1297** [comment] 2016-08-31 18:25
So, to clarify ... the issue is about the fact that ESLintBear breaks down if the file has no issues ?

Yes

**Comment by AbdealiJK** [comment] 2016-08-31 18:35
I've tested this out as much as I could, and ESLintBear does not break down for files that have no issues.

In such cases, the output is `[{"filePath":"<text>","messages":[],"errorCount":0,"warningCount":0}]` which gets parsed correctly as JSON and no results are found.

The `eslint --help` happens when the file given in is a zero-byte-file (content == ""). In such cases, eslint doesn't know what to do. Causing this error, but we have an  `if` which suppresses it and ignores it.

Closing this, please create a new issue if you face again.

**Comment by AbdealiJK** [comment] 2016-09-02 14:58
Gah ! I just realized how to reproduce this finally.
This happens when eslint has an error (Like an invalid config file).
So, this is similar to https://github.com/coala-analyzer/coala-bears/issues/730 as they both happen for the same reason

**Comment by sils1297** [comment] 2016-09-02 17:51
@AbdealiJK please note that https://github.com/coala-analyzer/coala-bears/pull/777 is happening at the same time

**Closed** 2016-09-03 16:46 UTC
Labels: type/bug
