### ISSUE TITLE
Remove clang installation

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-bears#303] opened 2016-03-30 13:39 UTC
right now a ton of stuff fails tests due to clang, we might temporarily remove it to see if it is the problem?

**Comment by Makman2** [comment] 2016-03-30 16:56
LLVM x64 was installed on the appveyor servers, and this is the cause of the problem. Hotfix already on its way on https://github.com/coala-analyzer/coala-bears/pull/304.
Closing in favor of https://github.com/coala-analyzer/coala-bears/issues/305 then.

**Closed by Makman2** 2016-03-30 16:56 UTC
Labels: difficulty/low, importance/high
