### ISSUE TITLE
Rust Linter

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala-bears#183] opened 2016-03-07 23:39 UTC
I'd like to work on a new bear for linting Rust code

https://doc.rust-lang.org/book/compiler-plugins.html#lint-plugins

**Comment by Makman2** [comment] 2016-03-08 18:14
Did you see #50?

**Comment by sils1297** [comment] 2016-03-08 18:29
Is this a dupe? If yes close it.

**Comment by Makman2** [comment] 2016-03-08 21:57
Marking this as duplicate of #50.

**Closed by Makman2** 2016-03-08 21:57 UTC
Labels: difficulty/low, status/duplicate
