### ISSUE TITLE
Swift Bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#336] opened 2016-04-21 22:40 UTC
Do we have something for swift yet? IIRC we planned something. How avbout https://github.com/sleekbyte/tailor

difficulty/low

**Comment by AbdealiJK** [comment] 2016-04-22 12:50
Closing this as it's a duplicate of https://github.com/coala-analyzer/coala-bears/issues/11

**Closed by AbdealiJK** 2016-04-22 12:50 UTC
Labels: difficulty/low
